version: '3.8'

services:
  web:
    build: .
    container_name: lab3-web
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/library
      - FLASK_APP=library_api:create_app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/library
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: lab3-db
    platform: linux/amd64
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    name: lab3_app-network
    driver: bridge

volumes:
  postgres_data:
    name: lab3_postgres_data 